version: '3.1'

services:

  db:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Piyush@123
      POSTGRES_DB: ff4j_demo_boot2
    networks:
      - ff4jpostgresdemo 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - ff4jpostgresdemo

# I want to access ny cluster from host      
networks:
  ff4jpostgresdemo:
    driver: bridge
